package fr.rob.game.infra.opcode

const val CMSG_LOG_INTO_WORLD = 0x01
const val SMSG_PLAYER_DESCRIPTION = 0x02
const val SMSG_NEARBY_OBJECT_UPDATE = 0x03
const val SMSG_MOVEMENT_HEARTBEAT = 0x04
const val CMSG_REMOVE_FROM_WORLD = 0x05
const val CMSG_PLAYER_MOVEMENT = 0x06
const val CMSG_CHEAT_TELEPORT = 0x98
const val SMSG_GAME_INITIALIZATION_SUCCEED = 0x99

val OPCODES_MAP = Array(0x99) { i ->
    when (i) {
        CMSG_LOG_INTO_WORLD -> "CMSG_LOG_INTO_WORLD"
        SMSG_PLAYER_DESCRIPTION -> "SMSG_PLAYER_DESCRIPTION"
        SMSG_NEARBY_OBJECT_UPDATE -> "SMSG_NEARBY_OBJECT_UPDATE"
        SMSG_MOVEMENT_HEARTBEAT -> "SMSG_MOVEMENT_HEARTBEAT"
        CMSG_REMOVE_FROM_WORLD -> "CMSG_REMOVE_FROM_WORLD"
        CMSG_PLAYER_MOVEMENT -> "CMSG_PLAYER_MOVEMENT"
        CMSG_CHEAT_TELEPORT -> "CMSG_CHEAT_TELEPORT"
        SMSG_GAME_INITIALIZATION_SUCCEED -> "SMSG_GAME_INITIALIZATION_SUCCEED"
        else -> "UNKNOWN"
    }
}
