// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: eas/Eas.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Fr.Raven.Proto.Message.Eas {

  /// <summary>Holder for reflection information generated from eas/Eas.proto</summary>
  public static partial class EasReflection {

    #region Descriptor
    /// <summary>File descriptor for eas/Eas.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static EasReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg1lYXMvRWFzLnByb3RvEhpmci5yYXZlbi5wcm90by5tZXNzYWdlLmVhcyLV",
            "AQoJRWFzUGFja2V0EjwKCGF1dGhUeXBlGAEgASgOMiouZnIucmF2ZW4ucHJv",
            "dG8ubWVzc2FnZS5lYXMuRWFzUGFja2V0LlR5cGUSTAoNZGV2QXV0aFBhY2tl",
            "dBgCIAEoCzIzLmZyLnJhdmVuLnByb3RvLm1lc3NhZ2UuZWFzLkRldkF1dGhl",
            "bnRpY2F0aW9uUGFja2V0SAAiJAoEVHlwZRIHCgNERVYQABIHCgNKV1QQARIK",
            "CgZPQVVUSDIQAkIWChRhdXRoZW50aWNhdGlvblBhY2tldCIpChdEZXZBdXRo",
            "ZW50aWNhdGlvblBhY2tldBIOCgZ1c2VySWQYASABKA0iPgoXRWFzQXV0aGVu",
            "dGljYXRpb25SZXN1bHQSIwobaXNBdXRoZW50aWNhdGVkU3VjY2Vzc2Z1bGx5",
            "GAEgASgIQgpCCEVhc1Byb3RvYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Fr.Raven.Proto.Message.Eas.EasPacket), global::Fr.Raven.Proto.Message.Eas.EasPacket.Parser, new[]{ "AuthType", "DevAuthPacket" }, new[]{ "AuthenticationPacket" }, new[]{ typeof(global::Fr.Raven.Proto.Message.Eas.EasPacket.Types.Type) }, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Fr.Raven.Proto.Message.Eas.DevAuthenticationPacket), global::Fr.Raven.Proto.Message.Eas.DevAuthenticationPacket.Parser, new[]{ "UserId" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Fr.Raven.Proto.Message.Eas.EasAuthenticationResult), global::Fr.Raven.Proto.Message.Eas.EasAuthenticationResult.Parser, new[]{ "IsAuthenticatedSuccessfully" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class EasPacket : pb::IMessage<EasPacket>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<EasPacket> _parser = new pb::MessageParser<EasPacket>(() => new EasPacket());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<EasPacket> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Fr.Raven.Proto.Message.Eas.EasReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public EasPacket() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public EasPacket(EasPacket other) : this() {
      authType_ = other.authType_;
      switch (other.AuthenticationPacketCase) {
        case AuthenticationPacketOneofCase.DevAuthPacket:
          DevAuthPacket = other.DevAuthPacket.Clone();
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public EasPacket Clone() {
      return new EasPacket(this);
    }

    /// <summary>Field number for the "authType" field.</summary>
    public const int AuthTypeFieldNumber = 1;
    private global::Fr.Raven.Proto.Message.Eas.EasPacket.Types.Type authType_ = global::Fr.Raven.Proto.Message.Eas.EasPacket.Types.Type.Dev;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Fr.Raven.Proto.Message.Eas.EasPacket.Types.Type AuthType {
      get { return authType_; }
      set {
        authType_ = value;
      }
    }

    /// <summary>Field number for the "devAuthPacket" field.</summary>
    public const int DevAuthPacketFieldNumber = 2;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Fr.Raven.Proto.Message.Eas.DevAuthenticationPacket DevAuthPacket {
      get { return authenticationPacketCase_ == AuthenticationPacketOneofCase.DevAuthPacket ? (global::Fr.Raven.Proto.Message.Eas.DevAuthenticationPacket) authenticationPacket_ : null; }
      set {
        authenticationPacket_ = value;
        authenticationPacketCase_ = value == null ? AuthenticationPacketOneofCase.None : AuthenticationPacketOneofCase.DevAuthPacket;
      }
    }

    private object authenticationPacket_;
    /// <summary>Enum of possible cases for the "authenticationPacket" oneof.</summary>
    public enum AuthenticationPacketOneofCase {
      None = 0,
      DevAuthPacket = 2,
    }
    private AuthenticationPacketOneofCase authenticationPacketCase_ = AuthenticationPacketOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AuthenticationPacketOneofCase AuthenticationPacketCase {
      get { return authenticationPacketCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearAuthenticationPacket() {
      authenticationPacketCase_ = AuthenticationPacketOneofCase.None;
      authenticationPacket_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as EasPacket);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(EasPacket other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (AuthType != other.AuthType) return false;
      if (!object.Equals(DevAuthPacket, other.DevAuthPacket)) return false;
      if (AuthenticationPacketCase != other.AuthenticationPacketCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (AuthType != global::Fr.Raven.Proto.Message.Eas.EasPacket.Types.Type.Dev) hash ^= AuthType.GetHashCode();
      if (authenticationPacketCase_ == AuthenticationPacketOneofCase.DevAuthPacket) hash ^= DevAuthPacket.GetHashCode();
      hash ^= (int) authenticationPacketCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (AuthType != global::Fr.Raven.Proto.Message.Eas.EasPacket.Types.Type.Dev) {
        output.WriteRawTag(8);
        output.WriteEnum((int) AuthType);
      }
      if (authenticationPacketCase_ == AuthenticationPacketOneofCase.DevAuthPacket) {
        output.WriteRawTag(18);
        output.WriteMessage(DevAuthPacket);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (AuthType != global::Fr.Raven.Proto.Message.Eas.EasPacket.Types.Type.Dev) {
        output.WriteRawTag(8);
        output.WriteEnum((int) AuthType);
      }
      if (authenticationPacketCase_ == AuthenticationPacketOneofCase.DevAuthPacket) {
        output.WriteRawTag(18);
        output.WriteMessage(DevAuthPacket);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (AuthType != global::Fr.Raven.Proto.Message.Eas.EasPacket.Types.Type.Dev) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) AuthType);
      }
      if (authenticationPacketCase_ == AuthenticationPacketOneofCase.DevAuthPacket) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(DevAuthPacket);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(EasPacket other) {
      if (other == null) {
        return;
      }
      if (other.AuthType != global::Fr.Raven.Proto.Message.Eas.EasPacket.Types.Type.Dev) {
        AuthType = other.AuthType;
      }
      switch (other.AuthenticationPacketCase) {
        case AuthenticationPacketOneofCase.DevAuthPacket:
          if (DevAuthPacket == null) {
            DevAuthPacket = new global::Fr.Raven.Proto.Message.Eas.DevAuthenticationPacket();
          }
          DevAuthPacket.MergeFrom(other.DevAuthPacket);
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            AuthType = (global::Fr.Raven.Proto.Message.Eas.EasPacket.Types.Type) input.ReadEnum();
            break;
          }
          case 18: {
            global::Fr.Raven.Proto.Message.Eas.DevAuthenticationPacket subBuilder = new global::Fr.Raven.Proto.Message.Eas.DevAuthenticationPacket();
            if (authenticationPacketCase_ == AuthenticationPacketOneofCase.DevAuthPacket) {
              subBuilder.MergeFrom(DevAuthPacket);
            }
            input.ReadMessage(subBuilder);
            DevAuthPacket = subBuilder;
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            AuthType = (global::Fr.Raven.Proto.Message.Eas.EasPacket.Types.Type) input.ReadEnum();
            break;
          }
          case 18: {
            global::Fr.Raven.Proto.Message.Eas.DevAuthenticationPacket subBuilder = new global::Fr.Raven.Proto.Message.Eas.DevAuthenticationPacket();
            if (authenticationPacketCase_ == AuthenticationPacketOneofCase.DevAuthPacket) {
              subBuilder.MergeFrom(DevAuthPacket);
            }
            input.ReadMessage(subBuilder);
            DevAuthPacket = subBuilder;
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the EasPacket message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      public enum Type {
        [pbr::OriginalName("DEV")] Dev = 0,
        [pbr::OriginalName("JWT")] Jwt = 1,
        [pbr::OriginalName("OAUTH2")] Oauth2 = 2,
      }

    }
    #endregion

  }

  public sealed partial class DevAuthenticationPacket : pb::IMessage<DevAuthenticationPacket>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<DevAuthenticationPacket> _parser = new pb::MessageParser<DevAuthenticationPacket>(() => new DevAuthenticationPacket());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<DevAuthenticationPacket> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Fr.Raven.Proto.Message.Eas.EasReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DevAuthenticationPacket() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DevAuthenticationPacket(DevAuthenticationPacket other) : this() {
      userId_ = other.userId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DevAuthenticationPacket Clone() {
      return new DevAuthenticationPacket(this);
    }

    /// <summary>Field number for the "userId" field.</summary>
    public const int UserIdFieldNumber = 1;
    private uint userId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint UserId {
      get { return userId_; }
      set {
        userId_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as DevAuthenticationPacket);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(DevAuthenticationPacket other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (UserId != other.UserId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (UserId != 0) hash ^= UserId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (UserId != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(UserId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (UserId != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(UserId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (UserId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(UserId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(DevAuthenticationPacket other) {
      if (other == null) {
        return;
      }
      if (other.UserId != 0) {
        UserId = other.UserId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            UserId = input.ReadUInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            UserId = input.ReadUInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class EasAuthenticationResult : pb::IMessage<EasAuthenticationResult>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<EasAuthenticationResult> _parser = new pb::MessageParser<EasAuthenticationResult>(() => new EasAuthenticationResult());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<EasAuthenticationResult> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Fr.Raven.Proto.Message.Eas.EasReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public EasAuthenticationResult() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public EasAuthenticationResult(EasAuthenticationResult other) : this() {
      isAuthenticatedSuccessfully_ = other.isAuthenticatedSuccessfully_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public EasAuthenticationResult Clone() {
      return new EasAuthenticationResult(this);
    }

    /// <summary>Field number for the "isAuthenticatedSuccessfully" field.</summary>
    public const int IsAuthenticatedSuccessfullyFieldNumber = 1;
    private bool isAuthenticatedSuccessfully_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool IsAuthenticatedSuccessfully {
      get { return isAuthenticatedSuccessfully_; }
      set {
        isAuthenticatedSuccessfully_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as EasAuthenticationResult);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(EasAuthenticationResult other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (IsAuthenticatedSuccessfully != other.IsAuthenticatedSuccessfully) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (IsAuthenticatedSuccessfully != false) hash ^= IsAuthenticatedSuccessfully.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (IsAuthenticatedSuccessfully != false) {
        output.WriteRawTag(8);
        output.WriteBool(IsAuthenticatedSuccessfully);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (IsAuthenticatedSuccessfully != false) {
        output.WriteRawTag(8);
        output.WriteBool(IsAuthenticatedSuccessfully);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (IsAuthenticatedSuccessfully != false) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(EasAuthenticationResult other) {
      if (other == null) {
        return;
      }
      if (other.IsAuthenticatedSuccessfully != false) {
        IsAuthenticatedSuccessfully = other.IsAuthenticatedSuccessfully;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            IsAuthenticatedSuccessfully = input.ReadBool();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            IsAuthenticatedSuccessfully = input.ReadBool();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
