version: '3.7'

networks:
  gamedb:

volumes:
  mysqldata:

services:
  protobuf:
    build:
      context: docker/protobuf
      args:
        - PROTOBUF_VERSION=3.14.0
    volumes:
      - .:/mnt/app

  migrator:
    build:
      context: docker/migrator
      args:
        - USER_ID=${USER_ID:-1000}
        - GROUP_ID=${GROUP_ID:-1000}
    volumes:
      - .:/mnt/app
    networks:
      - gamedb

  mysql_game:
    image: mysql:8.0.32
    volumes:
      - ./docker/mysql/docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/
      - mysqldata:/mnt/data
      - ./logs/mysql:/mnt/log
    ports:
      - '33060:3306'
    networks:
      - gamedb
    environment:
      MYSQL_ROOT_PASSWORD: pass
      TZ: Europe/Paris
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    healthcheck:
      test: "mysql -u$$MYSQL_USER -p$$MYSQL_PASSWORD -h127.0.0.1 -e 'SELECT 1;'"
      interval: 6s
      timeout: 10s
      retries: 10

