version: '3.7'

networks:
  gamedb:
  tests:

volumes:
  mysqldata:
  mysqlunitdata:
  gradlecache:

services:
  protobuf:
    build:
      context: docker/protobuf
      args:
        - PROTOBUF_VERSION=3.14.0
    volumes:
      - .:/mnt/app

  gradle:
    build:
      context: docker/gradle
      target: dev
      args:
        - USER_ID=${USER_ID:-1000}
        - GROUP_ID=${GROUP_ID:-1000}
    user: '$USER_ID:$GROUP_ID'
    volumes:
      - .:/mnt/app
      - gradlecache:/home/gradle/.gradle
    ports:
      - '5005:5005'
      - '5006:5006'
      - '5007:5007'
      - '55599:55599'
    networks:
      - gamedb
      - tests

  migrator:
    build:
      context: docker/migrator
      args:
        - USER_ID=${USER_ID:-1000}
        - GROUP_ID=${GROUP_ID:-1000}
    volumes:
      - .:/mnt/app
    networks:
      - gamedb
      - tests

  mysql_game:
    build:
      context: docker/mysql
      target: dev
      args:
        - USER_ID=${USER_ID:-1000}
        - GROUP_ID=${GROUP_ID:-1000}
    volumes:
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
      - mysqldata:/mnt/data
      - ./logs/mysql:/mnt/log
    ports:
      - '33060:3306'
    networks:
      - gamedb
    environment:
      MYSQL_USER: ${WORLD_MYSQL_USER}
      MYSQL_PASSWORD: ${WORLD_MYSQL_PASSWORD}
      MYSQL_HOST: ${WORLD_MYSQL_HOST}

  mysql_unit:
    build:
      context: docker/mysql
      target: unit
      args:
        - USER_ID=${USER_ID:-1000}
        - GROUP_ID=${GROUP_ID:-1000}
    volumes:
      - mysqlunitdata:/mnt/data
      - ./logs/mysql_unit:/mnt/log
    networks:
      - tests
    environment:
      MYSQL_USER: ${UNIT_MYSQL_USER}
      MYSQL_PASSWORD: ${UNIT_MYSQL_PASSWORD}
      MYSQL_DATABASE: ${UNIT_MYSQL_DATABASE}
