version: '3.7'

networks:
  gamedb:

volumes:
  mysqldata:

services:
  protobuf:
    build:
      context: docker/protobuf
      args:
        - PROTOBUF_VERSION=3.14.0
    volumes:
      - .:/mnt/app

  gradle:
    build:
      context: docker/gradle
      target: dev
      args:
        - USER_ID=${USER_ID:-1000}
        - GROUP_ID=${GROUP_ID:-1000}
    volumes:
      - .:/mnt/app
    ports:
      - 5005:5005
    networks:
      - gamedb

  migrator:
    build:
      context: docker/migrator
      args:
        - USER_ID=${USER_ID:-1000}
        - GROUP_ID=${GROUP_ID:-1000}
    volumes:
      - .:/mnt/app
    networks:
      - gamedb

  mysql_game:
    build:
      context: docker/mysql
      target: dev
      args:
        - USER_ID=${USER_ID:-1000}
        - GROUP_ID=${GROUP_ID:-1000}
    volumes:
      - mysqldata:/mnt/data
      - ./logs/mysql:/mnt/log
    ports:
      - 33060:3306
    networks:
      - gamedb
    environment:
      MYSQL_DATABASE: ${GAME_MYSQL_DATABASE}
      MYSQL_USER: ${GAME_MYSQL_USER}
      MYSQL_PASSWORD: ${GAME_MYSQL_PASSWORD}
      MYSQL_HOST: ${GAME_MYSQL_HOST}
