GRADLE_BIN = ./gradlew
GRADLE_ARGS =
GRADLE_CMD = ${GRADLE_BIN} ${GRADLE_ARGS}

DOCKER_COMPOSE_BIN = docker compose
DOCKER_COMPOSE_ARGS =
DOCKER_COMPOSE_CMD = ${DOCKER_COMPOSE_BIN} ${DOCKER_COMPOSE_ARGS}

DOCKER_COMPOSE_RUN_ARGS = --rm
DOCKER_COMPOSE_RUN_CMD = ${DOCKER_COMPOSE_CMD} run ${DOCKER_COMPOSE_RUN_ARGS}

ifdef CI_SERVER
DOCKER_COMPOSE_RUN_ARGS += -T
endif