GRADLE_BIN = ./gradlew
GRADLE_ARGS =
GRADLE_CMD = ${GRADLE_BIN} ${GRADLE_ARGS}

DOCKER_COMPOSE_BIN = docker compose
DOCKER_COMPOSE_ARGS =
DOCKER_COMPOSE_CMD = ${DOCKER_COMPOSE_BIN} ${DOCKER_COMPOSE_ARGS}

DOCKER_COMPOSE_RUN_ARGS = --rm
DOCKER_COMPOSE_RUN_CMD = ${DOCKER_COMPOSE_CMD} run ${DOCKER_COMPOSE_RUN_ARGS}

ifdef CI_SERVER
DOCKER_COMPOSE_RUN_ARGS += -T
endif

DOCKER_COMPOSE_ATLAS_RUN = ${DOCKER_COMPOSE_RUN_CMD} atlas
ATLAS_BIN = ${DOCKER_COMPOSE_ATLAS_RUN}

UNITY_BIN ?= unity
UNITY_BUILD_ARGS ?= --allow-install

E2E_DIR = build/e2e
E2E_DB_OPTS = -Dmysql_game.host=127.0.0.1 -Dmysql_game.tcp.3306=33062
