<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Authentication.proto

namespace Rob\Protos;

class Authentication
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
ç
Authentication.protofr.rob.entities"*
Auth
username (	
password (	B0BAuthenticationProtos 
Rob\\Protos‚
Rob\\Protosbproto3'
        , true);

        static::$is_initialized = true;
    }
}

