-- Create "accounts" table
CREATE TABLE `accounts` (`id` int unsigned NOT NULL AUTO_INCREMENT, `user_id` int unsigned NOT NULL, `is_administrator` bool NOT NULL, `name` varchar(255) NOT NULL, `banned_at` datetime NULL, `is_locked` bool NOT NULL DEFAULT 0, `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, `updated_at` timestamp NULL ON UPDATE CURRENT_TIMESTAMP, PRIMARY KEY (`id`), UNIQUE INDEX `user_id` (`user_id`)) CHARSET utf8mb3 COLLATE utf8mb3_general_ci;
-- Create "creature_templates" table
CREATE TABLE `creature_templates` (`id` int unsigned NOT NULL AUTO_INCREMENT, `name` varchar(255) NOT NULL, `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, `updated_at` timestamp NULL ON UPDATE CURRENT_TIMESTAMP, PRIMARY KEY (`id`)) CHARSET utf8mb3 COLLATE utf8mb3_general_ci;
-- Create "default_instances" table
CREATE TABLE `default_instances` (`id` int unsigned NOT NULL AUTO_INCREMENT, `map_id` int unsigned NOT NULL, `zone_id` int unsigned NOT NULL, `node_name` varchar(255) NOT NULL, `type` tinyint unsigned NOT NULL, `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, `updated_at` timestamp NULL ON UPDATE CURRENT_TIMESTAMP, PRIMARY KEY (`id`), INDEX `map_id` (`map_id`, `zone_id`)) CHARSET utf8mb3 COLLATE utf8mb3_general_ci;
-- Create "instances" table
CREATE TABLE `instances` (`id` int unsigned NOT NULL AUTO_INCREMENT, `map_id` int unsigned NOT NULL, `zone_id` int unsigned NOT NULL, `type` tinyint unsigned NOT NULL, `sub_type` tinyint unsigned NULL, `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, `updated_at` timestamp NULL ON UPDATE CURRENT_TIMESTAMP, PRIMARY KEY (`id`), INDEX `map_id` (`map_id`, `type`)) CHARSET utf8mb3 COLLATE utf8mb3_general_ci;
-- Create "orchestrators" table
CREATE TABLE `orchestrators` (`id` int unsigned NOT NULL AUTO_INCREMENT, `address` varchar(255) NOT NULL, `token` varchar(255) NOT NULL, `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, `updated_at` timestamp NULL ON UPDATE CURRENT_TIMESTAMP, PRIMARY KEY (`id`)) CHARSET utf8mb3 COLLATE utf8mb3_general_ci;
-- Create "security_bans" table
CREATE TABLE `security_bans` (`id` int unsigned NOT NULL AUTO_INCREMENT, `ip` varchar(255) NOT NULL, `service` varchar(255) NOT NULL, `end_at` datetime NOT NULL, `reason` varchar(255) NOT NULL, `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, `updated_at` timestamp NULL ON UPDATE CURRENT_TIMESTAMP, PRIMARY KEY (`id`), INDEX `ip` (`ip`)) CHARSET utf8mb3 COLLATE utf8mb3_general_ci;
-- Create "characters" table
CREATE TABLE `characters` (`id` int unsigned NOT NULL AUTO_INCREMENT, `account_id` int unsigned NULL, `name` varchar(255) NOT NULL, `level` tinyint unsigned NOT NULL, `position_x` float NOT NULL, `position_y` float NOT NULL, `position_z` float NOT NULL, `orientation` float NOT NULL, `last_selected_at` datetime NOT NULL, `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, `updated_at` timestamp NULL ON UPDATE CURRENT_TIMESTAMP, PRIMARY KEY (`id`), INDEX `account_id` (`account_id`), UNIQUE INDEX `name` (`name`), CONSTRAINT `characters_ibfk_1` FOREIGN KEY (`account_id`) REFERENCES `accounts` (`id`) ON UPDATE NO ACTION ON DELETE SET NULL) CHARSET utf8mb3 COLLATE utf8mb3_general_ci;
-- Create "objects" table
CREATE TABLE `objects` (`id` int unsigned NOT NULL AUTO_INCREMENT, `map_id` int unsigned NOT NULL, `template_id` int unsigned NOT NULL COMMENT "Foreign key on *_templates tables", `type` tinyint unsigned NOT NULL, `position_x` float NOT NULL COMMENT "X position on the map (not the zone)", `position_y` float NOT NULL COMMENT "Y position on the map (not the zone)", `position_z` float NOT NULL COMMENT "Z position on the map (not the zone)", `orientation` float NOT NULL, `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, `updated_at` timestamp NULL ON UPDATE CURRENT_TIMESTAMP, PRIMARY KEY (`id`), INDEX `map_id` (`map_id`), INDEX `type` (`type`, `template_id`)) CHARSET utf8mb3 COLLATE utf8mb3_general_ci;
-- Create "creatures" table
CREATE TABLE `creatures` (`id` int unsigned NOT NULL AUTO_INCREMENT, `object_id` int unsigned NULL, `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, `updated_at` timestamp NULL ON UPDATE CURRENT_TIMESTAMP, PRIMARY KEY (`id`), INDEX `object_id` (`object_id`), CONSTRAINT `creatures_ibfk_1` FOREIGN KEY (`object_id`) REFERENCES `objects` (`id`) ON UPDATE NO ACTION ON DELETE SET NULL) CHARSET utf8mb3 COLLATE utf8mb3_general_ci;
-- Create "tickets" table
CREATE TABLE `tickets` (`id` int unsigned NOT NULL AUTO_INCREMENT, `token` varchar(40) NOT NULL, `account_id` int unsigned NOT NULL, `character_id` int unsigned NOT NULL, `source_id` int unsigned NOT NULL, `target_id` int unsigned NOT NULL, `is_punched` bool NOT NULL, `expire_at` datetime NOT NULL, `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, `updated_at` timestamp NULL ON UPDATE CURRENT_TIMESTAMP, PRIMARY KEY (`id`), INDEX `account_id` (`account_id`), INDEX `character_id` (`character_id`), UNIQUE INDEX `token` (`token`), CONSTRAINT `tickets_ibfk_1` FOREIGN KEY (`account_id`) REFERENCES `accounts` (`id`) ON UPDATE NO ACTION ON DELETE CASCADE, CONSTRAINT `tickets_ibfk_2` FOREIGN KEY (`character_id`) REFERENCES `characters` (`id`) ON UPDATE NO ACTION ON DELETE CASCADE) CHARSET utf8mb3 COLLATE utf8mb3_general_ci;
-- Create "maps" table
CREATE TABLE `maps` (`id` int unsigned NOT NULL AUTO_INCREMENT, `name` varchar(255) NOT NULL, `width` int unsigned NOT NULL, `height` int unsigned NOT NULL, PRIMARY KEY (`id`)) CHARSET utf8mb3 COLLATE utf8mb3_general_ci;
-- Create "zones" table
CREATE TABLE `zones` (`id` int unsigned NOT NULL AUTO_INCREMENT, `map_id` int unsigned NULL, `name` varchar(255) NULL, `width` int unsigned NOT NULL, `height` int unsigned NOT NULL, `offset_x` float NOT NULL COMMENT "Represents the X coordinate of the origin point of the map", `offset_y` float NOT NULL COMMENT "Represents the Y coordinate of the origin point of the map", `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, `updated_at` timestamp NULL ON UPDATE CURRENT_TIMESTAMP, PRIMARY KEY (`id`), INDEX `map_id` (`map_id`), CONSTRAINT `zones_ibfk_1` FOREIGN KEY (`map_id`) REFERENCES `maps` (`id`) ON UPDATE NO ACTION ON DELETE SET NULL) CHARSET utf8mb3 COLLATE utf8mb3_general_ci;
